### ISSUE TITLE
Some pages do not load at all when directly linked

### ISSUE THREAD

**Issue by mikejones3** [v17development/flarum-seo#12]
Google search console started showing certain pages were not loading. I went to the page to investigate and it said:

An error occurred while trying to load this page.

I then went to my main page of my Flarum and that worked fine, and I navigated to the page and the same page worked. For example, if you go here directly it will fail:

https://www.seekadventure.net/d/43-thermarest-neoair-uberlite

But if you go to https://www.seekadventure.net first then look for that same thread and click it then it magically works. Basically, direct links do not work.

```
[2019-02-22 00:28:44] production.ERROR: Error: Call to a member function getAttribute() on null in /var/www/seekadventure.net/vendor/v17dev$
Stack trace:
#0 /var/www/seekadventure.net/vendor/v17development/flarum-seo/src/Managers/QADiscussion.php(59): V17Development\FlarumSeo\Managers\QADiscu$
#1 /var/www/seekadventure.net/vendor/v17development/flarum-seo/src/Listeners/PageListener.php(143): V17Development\FlarumSeo\Managers\QADis$
#2 /var/www/seekadventure.net/vendor/v17development/flarum-seo/src/Listeners/PageListener.php(106): V17Development\FlarumSeo\Listeners\Page$
#3 /var/www/seekadventure.net/vendor/flarum/core/src/Frontend/Frontend.php(65): V17Development\FlarumSeo\Listeners\PageListener->__invoke(O$
#4 /var/www/seekadventure.net/vendor/flarum/core/src/Frontend/Frontend.php(57): Flarum\Frontend\Frontend->populate(Object(Flarum\Frontend\D$
#5 /var/www/seekadventure.net/vendor/flarum/core/src/Frontend/Controller.php(34): Flarum\Frontend\Frontend->document(Object(Zend\Diactoros\$
#6 /var/www/seekadventure.net/vendor/flarum/core/src/Http/RouteHandlerFactory.php(40): Flarum\Frontend\Controller->handle(Object(Zend\Diact$
#7 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(67): Flarum\Http\RouteHandlerFactory->Flarum\Http\{c$
#8 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\DispatchRoute->process(Object$
#9 /var/www/seekadventure.net/vendor/reflar/stopforumspam/src/Middleware/RegisterMiddleware.php(75): Zend\Stratigility\Next->handle(Object($
#10 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Reflar\Stopforumspam\middleware\RegisterMiddleware-$
#11 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(58): Zend\Stratigility\Next->handle(Object$
#12 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\ShareErrorsFromSession->proc$
#13 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\Stratigility\Next->handle(Object(Zend\Diactor$
#14 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\SetLocale->process(Object(Ze$
#15 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(34): Zend\Stratigility\Next->handle(Objec$
#16 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\AuthenticateWithSession->pro$
#17 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Zend\Stratigility\Next->handle(Object(Zen$
#18 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\RememberFromCookie->process($
#19 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/StartSession.php(62): Zend\Stratigility\Next->handle(Object(Zend\Diac$
#20 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\StartSession->process(Object$
#21 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(48): Zend\Stratigility\Next->handle(Object(Zend\Di$
#22 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\CollectGarbage->process(Obje$
#23 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(29): Zend\Stratigility\Next->handle(Object(Zend\Dia$
#24 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\ParseJsonBody->process(Objec$
#25 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/HandleErrorsWithView.php(67): Zend\Stratigility\Next->handle(Object(Z$
#26 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\HandleErrorsWithView->proces$
#27 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(91): Zend\Stratigility\Next->handle(Object(Zen$
#28 /var/www/seekadventure.net/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\Stratigility\MiddlewarePipe->process(Obj$
#29 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\RequestHandler->process(Objec$
#30 /var/www/seekadventure.net/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\Stratigility\MiddlewarePipe->handle(Obj$
#31 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\BasePathRouter->process(Objec$
#32 /var/www/seekadventure.net/vendor/middlewares/base-path/src/BasePath.php(53): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diac$
#33 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\BasePath->process(Object(Zend$
#34 /var/www/seekadventure.net/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\Stratigility\MiddlewarePi$
#35 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Server.php(46): Zend\HttpHandlerRunner\RequestHandlerRunner->run()
#36 /var/www/seekadventure.net/public/index.php(18): Flarum\Http\Server->listen()
#37 {main}
 
[2019-02-22 00:47:36] production.ERROR: Error: Call to a member function getAttribute() on null in /var/www/seekadventure.net/vendor/v17dev$
Stack trace:
#0 /var/www/seekadventure.net/vendor/v17development/flarum-seo/src/Managers/QADiscussion.php(59): V17Development\FlarumSeo\Managers\QADiscu$
#1 /var/www/seekadventure.net/vendor/v17development/flarum-seo/src/Listeners/PageListener.php(143): V17Development\FlarumSeo\Managers\QADis$
#2 /var/www/seekadventure.net/vendor/v17development/flarum-seo/src/Listeners/PageListener.php(106): V17Development\FlarumSeo\Listeners\Page$
#3 /var/www/seekadventure.net/vendor/flarum/core/src/Frontend/Frontend.php(65): V17Development\FlarumSeo\Listeners\PageListener->__invoke(O$
#4 /var/www/seekadventure.net/vendor/flarum/core/src/Frontend/Frontend.php(57): Flarum\Frontend\Frontend->populate(Object(Flarum\Frontend\D$
#5 /var/www/seekadventure.net/vendor/flarum/core/src/Frontend/Controller.php(34): Flarum\Frontend\Frontend->document(Object(Zend\Diactoros\$
#6 /var/www/seekadventure.net/vendor/flarum/core/src/Http/RouteHandlerFactory.php(40): Flarum\Frontend\Controller->handle(Object(Zend\Diact$
#7 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(67): Flarum\Http\RouteHandlerFactory->Flarum\Http\{c$
#8 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\DispatchRoute->process(Object$
#9 /var/www/seekadventure.net/vendor/reflar/stopforumspam/src/Middleware/RegisterMiddleware.php(75): Zend\Stratigility\Next->handle(Object($
#10 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Reflar\Stopforumspam\middleware\RegisterMiddleware-$
#11 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(58): Zend\Stratigility\Next->handle(Object$
#12 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\ShareErrorsFromSession->proc$
#13 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\Stratigility\Next->handle(Object(Zend\Diactor$
#14 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\SetLocale->process(Object(Ze$
#15 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(34): Zend\Stratigility\Next->handle(Objec$
#16 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\AuthenticateWithSession->pro$
#17 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Zend\Stratigility\Next->handle(Object(Zen$
#18 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\RememberFromCookie->process($
#19 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/StartSession.php(62): Zend\Stratigility\Next->handle(Object(Zend\Diac$
#20 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\StartSession->process(Object$
#21 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(48): Zend\Stratigility\Next->handle(Object(Zend\Di$
#22 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\CollectGarbage->process(Obje$
#23 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(29): Zend\Stratigility\Next->handle(Object(Zend\Dia$
#24 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\ParseJsonBody->process(Objec$
#25 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/HandleErrorsWithView.php(67): Zend\Stratigility\Next->handle(Object(Z$
#26 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\HandleErrorsWithView->proces$
#27 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(91): Zend\Stratigility\Next->handle(Object(Zen$
#28 /var/www/seekadventure.net/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\Stratigility\MiddlewarePipe->process(Obj$
#29 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\RequestHandler->process(Objec$
#30 /var/www/seekadventure.net/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\Stratigility\MiddlewarePipe->handle(Obj$
#31 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\BasePathRouter->process(Objec$
#32 /var/www/seekadventure.net/vendor/middlewares/base-path/src/BasePath.php(53): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diac$
#33 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\BasePath->process(Object(Zend$
#34 /var/www/seekadventure.net/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\Stratigility\MiddlewarePi$
#35 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Server.php(46): Zend\HttpHandlerRunner\RequestHandlerRunner->run()
#36 /var/www/seekadventure.net/public/index.php(18): Flarum\Http\Server->listen()
#37 {main}
```

I also just tried clearing my cache to see if that fixed my above issue, but it did not. I also tried un-enabling and re-enabling the extension with clearing the cache in between and that also did not solve the issue.

**Comment by doweis** [comment]
Seems to be the same issue as https://github.com/v17development/flarum-seo/issues/11
