### ISSUE TITLE
Exception when the author of the discussion is a deleted user

### ISSUE THREAD

**Issue by matteocontrini** [v17development/flarum-seo#17]
I have a discussion where the user of the first post in the discussion has been deleted, and this extension is causing a 500 error response with this exception:

<details>

```
[2019-07-06 13:13:02] production.ERROR: Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [Flarum\User\User]. in /usr/local/
openresty/nginx/www/fibraclick-forum/vendor/illuminate/database/Eloquent/Builder.php:414
Stack trace:
#0 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/User/UserRepository.php(42): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/v17development/flarum-seo/src/Listeners/PageListener.php(380): Flarum\User\UserRepository->findO
rFail(NULL)
#2 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/v17development/flarum-seo/src/Managers/Discussion.php(115): V17Development\FlarumSeo\Listeners\P
ageListener->getUser(NULL)
#3 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/v17development/flarum-seo/src/Managers/Discussion.php(41): V17Development\FlarumSeo\Managers\Dis
cussion->createTags()
#4 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/v17development/flarum-seo/src/Listeners/PageListener.php(150): V17Development\FlarumSeo\Managers
\Discussion->__construct(Object(V17Development\FlarumSeo\Listeners\PageListener), Object(Flarum\Discussion\DiscussionRepository), '3158-ftth-tisca...')
#5 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/v17development/flarum-seo/src/Listeners/PageListener.php(116): V17Development\FlarumSeo\Listener
s\PageListener->determine()
#6 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/Frontend/Frontend.php(65): V17Development\FlarumSeo\Listeners\PageListener->__in
voke(Object(Flarum\Frontend\Document), Object(Zend\Diactoros\ServerRequest))
#7 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/Frontend/Frontend.php(57): Flarum\Frontend\Frontend->populate(Object(Flarum\Fron
tend\Document), Object(Zend\Diactoros\ServerRequest))
#8 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/Frontend/Controller.php(34): Flarum\Frontend\Frontend->document(Object(Zend\Diac
toros\ServerRequest))
#9 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/Http/RouteHandlerFactory.php(40): Flarum\Frontend\Controller->handle(Object(Zend
\Diactoros\ServerRequest))
#10 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(67): Flarum\Http\RouteHandlerFactory->Flarum\
Http\{closure}(Object(Zend\Diactoros\ServerRequest), Array)
#11 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\DispatchRoute->process
(Object(Zend\Diactoros\ServerRequest), Object(Closure))
#12 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(58): Zend\Stratigility\Next->handle(
Object(Zend\Diactoros\ServerRequest))
#13 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\ShareErrorsFromSession
->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#14 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\Stratigility\Next->handle(Object(Zend\D
iactoros\ServerRequest))
#15 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\SetLocale->process(Obj
ect(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#16 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(34): Zend\Stratigility\Next->handle
(Object(Zend\Diactoros\ServerRequest))
#17 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\AuthenticateWithSessio
n->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#18 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#19 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\RememberFromCookie->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#20 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/Http/Middleware/StartSession.php(62): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#21 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\StartSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#22 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(48): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#23 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\CollectGarbage->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#24 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(29): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#25 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\ParseJsonBody->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#26 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/Http/Middleware/HandleErrorsWithView.php(67): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#27 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\HandleErrorsWithView->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#28 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#29 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\Stratigility\MiddlewarePipe->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#30 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\RequestHandler->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#31 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#32 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\BasePathRouter->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#33 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/middlewares/base-path/src/BasePath.php(53): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#34 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\BasePath->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#35 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#36 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(72): Zend\Stratigility\MiddlewarePipe->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\EmptyPipelineHandler))
#37 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#38 /usr/local/openresty/nginx/www/fibraclick-forum/vendor/flarum/core/src/Http/Server.php(46): Zend\HttpHandlerRunner\RequestHandlerRunner->run()
#39 /usr/local/openresty/nginx/www/fibraclick-forum/public/index.php(22): Flarum\Http\Server->listen()
#40 {main}
```

</details>

**Comment by jaspervriends** [comment]
Thank you for the bug report! I've just tried this on a development environment and I could reproduce this!

I'll make sure to fix it tomorrow!
