### ISSUE TITLE
v17development-flarum-seo failed to initialize

### ISSUE THREAD

**Issue by SKevo18** [v17development/flarum-seo#98]
```
v17development-flarum-seo failed to initialize (fireApplicationError.ts:11:10)
TypeError: F() is undefined
    <anonymous> index.ts:45
    boot Application.tsx:281
    boot Application.tsx:279
    <anonymous> (index):240
[fireApplicationError.ts:12:10]
```

`Index.ts:45`

<img width="481" alt="screenshot" src="https://github.com/user-attachments/assets/2bd81d4d-fce0-4d4f-a2e7-c5694c54fbe5">

I am not sure what exactly causes this issue, as the other stacktrace belongs to the Flarum error handling source code. However, the extension seems to still load fine, despite the error message.

PHP Flarum info:

```
Flarum core: 1.8.7
PHP version: 8.3.12
MySQL version: 11.4.3-MariaDB-ubu2204
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, intl, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache
+--------------------------------------+---------+--------+
| Flarum Extensions                    |         |        |
+--------------------------------------+---------+--------+
| ID                                   | Version | Commit |
+--------------------------------------+---------+--------+
| flarum-markdown                      | v1.8.1  |        |
| flarum-flags                         | v1.8.1  |        |
| v17development-seo                   | v2.0.3  |        |
| askvortsov-rich-text                 | v2.1.7  |        |
| flarum-sticky                        | v1.8.1  |        |
| flarum-tags                          | v1.8.2  |        |
| flarum-lock                          | v1.8.1  |        |
| askvortsov-auto-moderator            | v0.1.3  |        |
| flarum-likes                         | v1.8.1  |        |
| afrux-forum-widgets-core             | v0.1.7  |        |
| flarum-suspend                       | v1.8.3  |        |
| flarum-approval                      | v1.8.2  |        |
| v17development-blog                  | v0.8.0  |        |
| v17development-user-badges           | v1.1.0  |        |
| therealsujitk-gifs                   | v4.1.1  |        |
| the-turk-stickiest                   | 3.0.1   |        |
| sycho-move-posts                     | v0.1.7  |        |
| ralkage-hcaptcha                     | 1.0.0   |        |
| nearata-no-self-likes                | v1.2.1  |        |
| migratetoflarum-canonical            | 1.0.0   |        |
| mickmelon-coloured-usernames         | 0.1.1   |        |
| matteocontrini-imgur-upload          | v3.9.1  |        |
| katosdev-signature                   | 1.6     |        |
| justoverclock-purify                 | 0.1.7   |        |
| justoverclock-hot-discussions        | 0.1.2   |        |
| justoverclock-edit-posts             | 0.1.1   |        |
| justoverclock-custom-html-widget     | 0.1.4   |        |
| justoverclock-contactme              | 0.2.3   |        |
| ianm-synopsis                        | 1.3.4   |        |
| ianm-syndication                     | 1.3.4   |        |
| ianm-html-head                       | 1.2.3   |        |
| fof-username-request                 | 1.2.4   |        |
| fof-user-directory                   | 1.3.3   |        |
| fof-user-bio                         | 1.4.0   |        |
| fof-upload                           | 1.5.5   |        |
| fof-split                            | 1.1.1   |        |
| fof-sitemap                          | 2.2.1   |        |
| fof-share-social                     | 1.2.0   |        |
| fof-profile-image-crop               | 1.1.6   |        |
| fof-polls                            | 2.2.8   |        |
| fof-nightmode                        | 1.6.0   |        |
| fof-merge-discussions                | 1.4.1   |        |
| fof-links                            | 1.3.0   |        |
| fof-linguist                         | 1.1.2   |        |
| fof-impersonate                      | 1.1.1   |        |
| fof-ignore-users                     | 1.2.1   |        |
| fof-formatting                       | 1.0.3   |        |
| fof-default-user-preferences         | 1.2.1   |        |
| fof-default-group                    | 1.1.2   |        |
| fof-ban-ips                          | 1.1.1   |        |
| fof-anti-spam                        | 1.1.2   |        |
| flarum-subscriptions                 | v1.8.1  |        |
| flarum-statistics                    | v1.8.1  |        |
| flarum-mentions                      | v1.8.4  |        |
| flarum-lang-english                  | v1.8.0  |        |
| flarum-bbcode                        | v1.8.0  |        |
| clarkwinkelmann-shadow-ban           | 1.1.0   |        |
| clarkwinkelmann-first-post-approval  | 1.0.1   |        |
| clarkwinkelmann-discussion-bookmarks | 2.0.1   |        |
| askvortsov-moderator-warnings        | v0.6.3  |        |
| askvortsov-categories                | v3.1.0  |        |
| afrux-top-posters-widget             | v0.1.4  |        |
| afrux-online-users-widget            | v0.1.6  |        |
| afrux-news-widget                    | v0.1.1  |        |
| afrux-forum-stats-widget             | v0.1.1  |        |
| acpl-mobile-tab                      | 1.4.4   |        |
+--------------------------------------+---------+--------+
Base URL: https://coffeetime.freeflarum.com
Installation path: /data/host/coffeetime
Queue driver: sync
Session driver: file
Scheduler status: Never run
Mail driver: mail
Debug mode: off
```

**Comment by efast1568** [comment]
I encountered the same issue.

**Comment by ismayilpoyraz** [comment]
if i open blog extension ı take same issue

**Comment by appsyscode** [comment]
I have the same error message

**Comment by Xbeed** [comment]
I encountered the similar issue with blog extension enabled. 

`v17development-flarum-seo failed to initialize
fireApplicationError.ts:12 TypeError: Cannot read properties of undefined (reading 'prototype')
    at index.ts:45:3
    at Application.tsx:281:9
    at Array.forEach (<anonymous>)
    at Proxy.<anonymous> (Application.tsx:279:33)
    at <anonymous>:8:33
    at t.activateScript (rocket-loader.min.js:1:11855)
    at rocket-loader.min.js:1:11052
    at t.run (rocket-loader.min.js:1:11259)
    at rocket-loader.min.js:1:11156
    at HTMLScriptElement.<anonymous> (rocket-loader.min.js:1:670)`

**Comment by jaspervriends** [comment]
Tagged [v2.0.4](https://github.com/v17development/flarum-seo/releases/tag/v2.0.4) which should fix the above issue! Thanks for reporting!
